ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
  # -   id: ...
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch=main]

  -   repo: https://github.com/hadialqattan/pycln
      rev: v2.6.0
      hooks:
      - id: pycln

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  -   repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.15.8
      hooks:
        - id: ruff
          args: [--fix]
        - id: ruff-format
